sudo: false
language: node_js
env:
  global:
  - CXX=g++-4.8
  - secure: Z/qM5q5U+cCPjGBh2JyBxss6DS0yRZeilIweJF7ibqpogSK97YH+pxQh7AOzBTNgkl1k5L1hOqcpocJ+PAGA9wCUpThUUNpKfmHoZcV68zUEtS+FmOIdDWHDUQX9s31TmLfFZSMbmGQpxXU42Sj5z7pcpb40wcf4cwP1diKGkBl18fpQ4Rdh/uIksB+37M2AzpN9PVs3qGjUNSW0djXzuZYbtNpvYoXgwYk0jRqo9NMKaTqqkSukNjZJXvAOS9bO8BcvPz3W86AnIEdImOh3eaicaJD0FZidkCyR2rBs0Z7PTkeu+okS0OiWnE0X3t4nC+ogrFU2mwEM5RSpIVw8RsaZ6CArO6ic2T3Vri6cfr438O5PCxe90owBmY+fbPPeZ4kV8ai4W6xWoSgLR6kRalWj4lgW3mCKBhNJPXmiBXgf6GD0Al2cY35RiBcggKJML6B/IrYK0W+YdWD2A1TlVqH6eSXY4sj+7b7BzgvULRFrI1LSkmUYl1pNi94UKT00U9oSX2gZzI8w+MAjgMSgVafr9pnHWZjCMxYfZNyIGVpHCRv+Rnf4jSFvh/h7uzB8PS3gz1OjOeg5NtLu8VbzzHWJLyoJepoaFg27LYLvU9IoTtD22xPa2YW96aAYSvCeqgTtRBwPSTkAFMj/RKt7Jlv/xKuGNkRjrYYWm4+LA4s=
  - secure: MzT3mWcY+8nU7vWe/Lm5X1NY5wW+unvtoztvtVDGEZCqX2H8v8yBwZnPHm/AoMADAgpLxFBUCL2zBxYYdjz7TvXfHCanD2v0UIjF/qR2/x8uwkAdod1MMxlalEMRpcv6+qEaXlg4zGOH4VKtAa7V78JtbYzuHQmwYiLj1b77yZmSX/unPxPVSLGNT+jehdbdJshjbDY26buJHoVHoX9g9T1S6kzQwAeKfOe9DwGtqzcQ624TPo74O61R/TBqeSBKhK6QuxV8+rj5Qw/HHEzFKKKM6bV1ndS61NkGJ7dqStFHYKFZGj43fZISQ52UVmJuTbD/ypRwW6HsxHHoIQ+IcXSAtqJaPQPcPYSIaBOKF+RXV35ovFFNo7oUQ1/Ym8MSpV4/sE88Erj4rc0SwuzRPRl6CmsK4q+I//Qn/EQd2joN4mAoEcbOqzMJQgF28/+VKCGKKGjD4Whe/mUlrEYeoQUnHKFiPGS09fH4PMyGQ/62oHPRgL5VefDxY3n5v1KvZVgZVIZu7sUqSXlKWkbZ8KCZ11TgEXn5R6gJzXi8IsIokHZdHLf9MKvfTRweLZm+1ixeMPG/9lwdifzfKxwC+/XFPEZjbhjDjwjLerN65u7CZLcaxeu765SvDaSJ+D7LyKJYD9Jd543cS/NunBbR7Xe+qRPRqcaj4ya9LQQNgdo=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
cache:
  directories:
  - node_modules
notifications:
  email:
    on_success: never
    on_failure: always
before_install:
- npm i -g npm@latest
- npm i -g yarn
- npm config set progress=false
install:
- yarn
script:
- npm start
after_script:
- npm test
